spring:
  application:
    name: pandq
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/grad-changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
