spring:
  datasource:
    url: jdbc:postgresql://ep-odd-haze-a1jrt8am-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_SeYsGABzP93a
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:

    url: ${SPRING_APPLICATION_URL:http://localhost:3000}
