spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/GRAD}
    username: ${SPRING_DATASOURCE_USERNAME:dbadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:dbadmin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  application:

    url: ${SPRING_APPLICATION_URL:http://localhost:3000}
